version: "3.7"
services:
  web:
    build: .
    env_file:
      - ./.env
    environment:
      - DATABASE_URI=sqlite:////db/data_subscriptions.db
    volumes:
      - ./data_subscriptions:/code/data_subscriptions
      - ./tests:/code/tests
      - ./db/:/db/
    ports:
      - "5000:5000"
