"""add_username_datasetname_to_subscription

Revision ID: 288f9ebd4d57
Revises: d0e8f7a70e6c
Create Date: 2020-05-12 07:41:18.719183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "288f9ebd4d57"
down_revision = "d0e8f7a70e6c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("subscription", sa.Column("dataset_name", sa.Text(), nullable=True))
    op.add_column("subscription", sa.Column("user_name", sa.Text(), nullable=True))
    op.execute("UPDATE subscription SET user_name = 'N/A'")
    op.alter_column("subscription", "user_name", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subscription", "user_name")
    op.drop_column("subscription", "dataset_name")
    # ### end Alembic commands ###
