"""add_composite_uniqueness_constraint_to_subscription

Revision ID: 9e3e665c6a2e
Revises: 53f520a5568f
Create Date: 2020-03-27 11:26:39.768783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9e3e665c6a2e"
down_revision = "53f520a5568f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("subscription_dataset_id_key", "subscription", type_="unique")
    op.drop_constraint("subscription_user_id_key", "subscription", type_="unique")
    op.create_unique_constraint(None, "subscription", ["dataset_id", "user_id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "subscription", type_="unique")
    op.create_unique_constraint("subscription_user_id_key", "subscription", ["user_id"])
    op.create_unique_constraint(
        "subscription_dataset_id_key", "subscription", ["dataset_id"]
    )
    # ### end Alembic commands ###
