"""add_email_to_subscriptions

Revision ID: cfc89c5e14c7
Revises: 288f9ebd4d57
Create Date: 2020-05-25 19:34:28.438774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cfc89c5e14c7"
down_revision = "288f9ebd4d57"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("subscription", sa.Column("email", sa.Text(), nullable=True))
    op.execute("UPDATE subscription SET email = 'sample@email.com'")
    op.alter_column("subscription", "email", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subscription", "email")
    # ### end Alembic commands ###
